/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hehehe.servicebuilder.model.impl;

import com.hehehe.servicebuilder.model.BookAuthor;
import com.hehehe.servicebuilder.service.BookAuthorLocalServiceUtil;

/**
 * The extended model base implementation for the BookAuthor service. Represents a row in the &quot;BookServiceBuilder_BookAuthor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BookAuthorImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BookAuthorImpl
 * @see BookAuthor
 * @generated
 */
public abstract class BookAuthorBaseImpl
	extends BookAuthorModelImpl implements BookAuthor {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a book author model instance should use the <code>BookAuthor</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			BookAuthorLocalServiceUtil.addBookAuthor(this);
		}
		else {
			BookAuthorLocalServiceUtil.updateBookAuthor(this);
		}
	}

}