/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hehehe.servicebuilder.model.impl;

import com.hehehe.servicebuilder.model.Subtitle;
import com.hehehe.servicebuilder.model.SubtitleModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Subtitle service. Represents a row in the &quot;BookServiceBuilder_Subtitle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SubtitleModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SubtitleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SubtitleImpl
 * @generated
 */
@JSON(strict = true)
public class SubtitleModelImpl
	extends BaseModelImpl<Subtitle> implements SubtitleModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a subtitle model instance should use the <code>Subtitle</code> interface instead.
	 */
	public static final String TABLE_NAME = "BookServiceBuilder_Subtitle";

	public static final Object[][] TABLE_COLUMNS = {
		{"subtitleId", Types.VARCHAR}, {"name", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("subtitleId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BookServiceBuilder_Subtitle (subtitleId VARCHAR(75) not null primary key,name VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table BookServiceBuilder_Subtitle";

	public static final String ORDER_BY_JPQL =
		" ORDER BY subtitle.subtitleId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BookServiceBuilder_Subtitle.subtitleId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SUBTITLEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SubtitleModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _subtitleId;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setSubtitleId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _subtitleId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return Subtitle.class;
	}

	@Override
	public String getModelClassName() {
		return Subtitle.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Subtitle, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Subtitle, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Subtitle, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Subtitle)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Subtitle, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Subtitle, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Subtitle)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Subtitle, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Subtitle, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Subtitle, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Subtitle, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Subtitle, Object>>();

			attributeGetterFunctions.put("subtitleId", Subtitle::getSubtitleId);
			attributeGetterFunctions.put("name", Subtitle::getName);
			attributeGetterFunctions.put("createDate", Subtitle::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Subtitle::getModifiedDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Subtitle, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Subtitle, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Subtitle, ?>>();

			attributeSetterBiConsumers.put(
				"subtitleId",
				(BiConsumer<Subtitle, String>)Subtitle::setSubtitleId);
			attributeSetterBiConsumers.put(
				"name", (BiConsumer<Subtitle, String>)Subtitle::setName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Subtitle, Date>)Subtitle::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Subtitle, Date>)Subtitle::setModifiedDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getSubtitleId() {
		if (_subtitleId == null) {
			return "";
		}
		else {
			return _subtitleId;
		}
	}

	@Override
	public void setSubtitleId(String subtitleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_subtitleId = subtitleId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public Subtitle toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Subtitle>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SubtitleImpl subtitleImpl = new SubtitleImpl();

		subtitleImpl.setSubtitleId(getSubtitleId());
		subtitleImpl.setName(getName());
		subtitleImpl.setCreateDate(getCreateDate());
		subtitleImpl.setModifiedDate(getModifiedDate());

		subtitleImpl.resetOriginalValues();

		return subtitleImpl;
	}

	@Override
	public Subtitle cloneWithOriginalValues() {
		SubtitleImpl subtitleImpl = new SubtitleImpl();

		subtitleImpl.setSubtitleId(
			this.<String>getColumnOriginalValue("subtitleId"));
		subtitleImpl.setName(this.<String>getColumnOriginalValue("name"));
		subtitleImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		subtitleImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));

		return subtitleImpl;
	}

	@Override
	public int compareTo(Subtitle subtitle) {
		String primaryKey = subtitle.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Subtitle)) {
			return false;
		}

		Subtitle subtitle = (Subtitle)object;

		String primaryKey = subtitle.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Subtitle> toCacheModel() {
		SubtitleCacheModel subtitleCacheModel = new SubtitleCacheModel();

		subtitleCacheModel.subtitleId = getSubtitleId();

		String subtitleId = subtitleCacheModel.subtitleId;

		if ((subtitleId != null) && (subtitleId.length() == 0)) {
			subtitleCacheModel.subtitleId = null;
		}

		subtitleCacheModel.name = getName();

		String name = subtitleCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			subtitleCacheModel.name = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			subtitleCacheModel.createDate = createDate.getTime();
		}
		else {
			subtitleCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			subtitleCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			subtitleCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return subtitleCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Subtitle, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Subtitle, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Subtitle, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Subtitle)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Subtitle>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Subtitle.class, ModelWrapper.class);

	}

	private String _subtitleId;
	private String _name;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		Function<Subtitle, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Subtitle)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("subtitleId", _subtitleId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("subtitleId", 1L);

		columnBitmasks.put("name", 2L);

		columnBitmasks.put("createDate", 4L);

		columnBitmasks.put("modifiedDate", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Subtitle _escapedModel;

}