/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hehehe.servicebuilder.model.impl;

import com.hehehe.servicebuilder.model.Subtitle;
import com.hehehe.servicebuilder.service.SubtitleLocalServiceUtil;

/**
 * The extended model base implementation for the Subtitle service. Represents a row in the &quot;BookServiceBuilder_Subtitle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SubtitleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SubtitleImpl
 * @see Subtitle
 * @generated
 */
public abstract class SubtitleBaseImpl
	extends SubtitleModelImpl implements Subtitle {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a subtitle model instance should use the <code>Subtitle</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SubtitleLocalServiceUtil.addSubtitle(this);
		}
		else {
			SubtitleLocalServiceUtil.updateSubtitle(this);
		}
	}

}