/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hehehe.servicebuilder.model;

import com.hehehe.servicebuilder.service.persistence.BookAuthorPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the BookAuthor service. Represents a row in the &quot;BookServiceBuilder_BookAuthor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.hehehe.servicebuilder.model.impl.BookAuthorModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.hehehe.servicebuilder.model.impl.BookAuthorImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BookAuthor
 * @generated
 */
@ProviderType
public interface BookAuthorModel extends BaseModel<BookAuthor> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a book author model instance should use the {@link BookAuthor} interface instead.
	 */

	/**
	 * Returns the primary key of this book author.
	 *
	 * @return the primary key of this book author
	 */
	public BookAuthorPK getPrimaryKey();

	/**
	 * Sets the primary key of this book author.
	 *
	 * @param primaryKey the primary key of this book author
	 */
	public void setPrimaryKey(BookAuthorPK primaryKey);

	/**
	 * Returns the book ID of this book author.
	 *
	 * @return the book ID of this book author
	 */
	@AutoEscape
	public String getBookId();

	/**
	 * Sets the book ID of this book author.
	 *
	 * @param bookId the book ID of this book author
	 */
	public void setBookId(String bookId);

	/**
	 * Returns the author ID of this book author.
	 *
	 * @return the author ID of this book author
	 */
	@AutoEscape
	public String getAuthorId();

	/**
	 * Sets the author ID of this book author.
	 *
	 * @param authorId the author ID of this book author
	 */
	public void setAuthorId(String authorId);

	/**
	 * Returns the create date of this book author.
	 *
	 * @return the create date of this book author
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this book author.
	 *
	 * @param createDate the create date of this book author
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this book author.
	 *
	 * @return the modified date of this book author
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this book author.
	 *
	 * @param modifiedDate the modified date of this book author
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public BookAuthor cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}