/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hehehe.servicebuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Book service. Represents a row in the &quot;BookServiceBuilder_Book&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.hehehe.servicebuilder.model.impl.BookModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.hehehe.servicebuilder.model.impl.BookImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Book
 * @generated
 */
@ProviderType
public interface BookModel extends BaseModel<Book> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a book model instance should use the {@link Book} interface instead.
	 */

	/**
	 * Returns the primary key of this book.
	 *
	 * @return the primary key of this book
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this book.
	 *
	 * @param primaryKey the primary key of this book
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the book ID of this book.
	 *
	 * @return the book ID of this book
	 */
	@AutoEscape
	public String getBookId();

	/**
	 * Sets the book ID of this book.
	 *
	 * @param bookId the book ID of this book
	 */
	public void setBookId(String bookId);

	/**
	 * Returns the title of this book.
	 *
	 * @return the title of this book
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this book.
	 *
	 * @param title the title of this book
	 */
	public void setTitle(String title);

	/**
	 * Returns the create date of this book.
	 *
	 * @return the create date of this book
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this book.
	 *
	 * @param createDate the create date of this book
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this book.
	 *
	 * @return the modified date of this book
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this book.
	 *
	 * @param modifiedDate the modified date of this book
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the description of this book.
	 *
	 * @return the description of this book
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this book.
	 *
	 * @param description the description of this book
	 */
	public void setDescription(String description);

	/**
	 * Returns the thumbnail of this book.
	 *
	 * @return the thumbnail of this book
	 */
	@AutoEscape
	public String getThumbnail();

	/**
	 * Sets the thumbnail of this book.
	 *
	 * @param thumbnail the thumbnail of this book
	 */
	public void setThumbnail(String thumbnail);

	/**
	 * Returns the published_year of this book.
	 *
	 * @return the published_year of this book
	 */
	public Integer getPublished_year();

	/**
	 * Sets the published_year of this book.
	 *
	 * @param published_year the published_year of this book
	 */
	public void setPublished_year(Integer published_year);

	/**
	 * Returns the num_pages of this book.
	 *
	 * @return the num_pages of this book
	 */
	public Integer getNum_pages();

	/**
	 * Sets the num_pages of this book.
	 *
	 * @param num_pages the num_pages of this book
	 */
	public void setNum_pages(Integer num_pages);

	/**
	 * Returns the price of this book.
	 *
	 * @return the price of this book
	 */
	public Integer getPrice();

	/**
	 * Sets the price of this book.
	 *
	 * @param price the price of this book
	 */
	public void setPrice(Integer price);

	/**
	 * Returns the stock of this book.
	 *
	 * @return the stock of this book
	 */
	public Integer getStock();

	/**
	 * Sets the stock of this book.
	 *
	 * @param stock the stock of this book
	 */
	public void setStock(Integer stock);

	/**
	 * Returns the subtitle ID of this book.
	 *
	 * @return the subtitle ID of this book
	 */
	@AutoEscape
	public String getSubtitleId();

	/**
	 * Sets the subtitle ID of this book.
	 *
	 * @param subtitleId the subtitle ID of this book
	 */
	public void setSubtitleId(String subtitleId);

	/**
	 * Returns the category ID of this book.
	 *
	 * @return the category ID of this book
	 */
	@AutoEscape
	public String getCategoryId();

	/**
	 * Sets the category ID of this book.
	 *
	 * @param categoryId the category ID of this book
	 */
	public void setCategoryId(String categoryId);

	@Override
	public Book cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}