/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hehehe.servicebuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Subtitle service. Represents a row in the &quot;BookServiceBuilder_Subtitle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.hehehe.servicebuilder.model.impl.SubtitleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.hehehe.servicebuilder.model.impl.SubtitleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Subtitle
 * @generated
 */
@ProviderType
public interface SubtitleModel extends BaseModel<Subtitle> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a subtitle model instance should use the {@link Subtitle} interface instead.
	 */

	/**
	 * Returns the primary key of this subtitle.
	 *
	 * @return the primary key of this subtitle
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this subtitle.
	 *
	 * @param primaryKey the primary key of this subtitle
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the subtitle ID of this subtitle.
	 *
	 * @return the subtitle ID of this subtitle
	 */
	@AutoEscape
	public String getSubtitleId();

	/**
	 * Sets the subtitle ID of this subtitle.
	 *
	 * @param subtitleId the subtitle ID of this subtitle
	 */
	public void setSubtitleId(String subtitleId);

	/**
	 * Returns the name of this subtitle.
	 *
	 * @return the name of this subtitle
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this subtitle.
	 *
	 * @param name the name of this subtitle
	 */
	public void setName(String name);

	/**
	 * Returns the create date of this subtitle.
	 *
	 * @return the create date of this subtitle
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this subtitle.
	 *
	 * @param createDate the create date of this subtitle
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this subtitle.
	 *
	 * @return the modified date of this subtitle
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this subtitle.
	 *
	 * @param modifiedDate the modified date of this subtitle
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public Subtitle cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}