/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hehehe.servicebuilder.service.base;

import com.hehehe.servicebuilder.model.Subtitle;
import com.hehehe.servicebuilder.service.SubtitleService;
import com.hehehe.servicebuilder.service.persistence.AuthorPersistence;
import com.hehehe.servicebuilder.service.persistence.BookAuthorPersistence;
import com.hehehe.servicebuilder.service.persistence.BookPersistence;
import com.hehehe.servicebuilder.service.persistence.CategoryPersistence;
import com.hehehe.servicebuilder.service.persistence.SubtitlePersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;

import java.sql.Connection;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the subtitle remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.hehehe.servicebuilder.service.impl.SubtitleServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.hehehe.servicebuilder.service.impl.SubtitleServiceImpl
 * @generated
 */
public abstract class SubtitleServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, IdentifiableOSGiService, SubtitleService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>SubtitleService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.hehehe.servicebuilder.service.SubtitleServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			SubtitleService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		subtitleService = (SubtitleService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return SubtitleService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Subtitle.class;
	}

	protected String getModelClassName() {
		return Subtitle.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = subtitlePersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected AuthorPersistence authorPersistence;

	@Reference
	protected BookPersistence bookPersistence;

	@Reference
	protected BookAuthorPersistence bookAuthorPersistence;

	@Reference
	protected CategoryPersistence categoryPersistence;

	@Reference
	protected com.hehehe.servicebuilder.service.SubtitleLocalService
		subtitleLocalService;

	protected SubtitleService subtitleService;

	@Reference
	protected SubtitlePersistence subtitlePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		SubtitleServiceBaseImpl.class);

}